### PR TITLE
Parse really long doubles

### LINKED ISSUE #40: Parse really long doubles and throw away the extra precision
We should be able to parse really long doubles, but at the moment fail hard on this. An example is `12345678901234567890` which is actually too big to fit in an int64, so we fail hard. In comparison `read "12345678901234567890"` produces the result `1.2345678901234567e19`: note that the last `89` are thrown away.

So the plan to do this:
`anemone_string_to_i64_v128` and `anemone_string_to_i64` should parse the first 19 digits and throw away the rest, but if there are remaining digits return the number of extra ones. We could encode this as a negative error code with the number of digits.

That way the double parsing can check if the digits is > 0 and if so increase the exponent or whatever.

Crazy SSE below:

```
        if (ANEMONE_UNLIKELY(index == 16)) {
            in              += 16;
            m                = anemone_sse_load_bytes128(in, pe);
            index            = anemone_sse_first_nondigit(m);
            if (index > buffer_size) {
                index = buffer_size;
            }
            buffer_size -= index;
            if (ANEMONE_UNLIKELY(index > 3)) {
// At this point we know there are more digits than we can handle, so:
// if index == 16 loop, read again, keep going until we find a non-digit, counting number of extra digits
// if index < 16 we know there are index-3 extra digits
// we should no longer return here, but instead cap index to 3 and perform parsing as usual,
// returning extra digits as error code
                return 1;
            }

            m                        = _mm_subs_epi8(m, zeros);
            const uint64_t i3        = anemone_string_to_i64_v128_first_eight(m, index);
            const uint64_t mul3 = powers_of_ten[index];
            int_out = int_out * mul3 + i3;

        }
```

### PR DESCRIPTION
**Pull request by amosr**
proof of concept, it works but needs cleaning up. initial benchmarking seems to be no real difference in runtime, but will check again.

fixes #40 
/jury approved @jystic

### CODE REVIEW

**Comment by amosr** [comment]
! @jystic @erikd-ambiata @tranma 

there are still two issues:
```
strtod "0.0000000000000000000000001" == Just 0.0
strtod "0.0e12345678901234567890" == Nothing
```

first one can be fixed by stripping leading zeroes in `string_to_ui64` instead of `string_to_double`

second one can be fixed, but ???

**Comment by erikd-ambiata** [comment]
Shouldn't `strtod "0.0e12345678901234567890"` return `0.0`?

**Comment by amosr** [comment]
Yeah, it should. I didn't want to spend that much time thinking about such a stupid case, but I might as well fix it

```
λ read "0.0e12345678901234567890" :: Double
Infinity
```

**Comment by erikd-ambiata** [comment]
Its better to find all the crazy edge cases now, fix/handle them in some logically consistent manner, and never have to worry about them again.

**Comment by amosr** [comment]
Will look at `0.0000000000000000001` case tomorrow, I think I need a special case when the integer part is `0`. If the integer part is anything other than 0, the fractional bit would get thrown away due to lack of precision.

**Comment by amosr** [comment]
Also todo: add new tests that add 20 or so zeros before the fractional part and before the exponent part

**Comment by amosr** [comment]
```
read "1e000000000000000000000000000000000000001" = 10
```

File: csrc/anemone_atoi_sse.c [hunk 1]
```diff
@@ -125,14 +183,22 @@ error_t anemone_string_to_i64_v128 (char **pp, char *pe, int64_t *out_val)
     int64_t sign             = 1;
 
     if (in[0] == '-') {
-        (*pp)++;
+        in++;
```
Comment (jystic) [inline csrc/anemone_atoi_sse.c]: anf 👍

**Comment by amosr** [comment]
Doubles are crazy. Apparently glibc uses big integers from libgmp to parse doubles. I don't know whether this affects us. I kind of doubt the attoparsec one allows the kind of crazy precision needed by big integers, so if that's sufficient this should be.

http://www.exploringbinary.com/how-glibc-strtod-works/
https://sourceware.org/git/?p=glibc.git;a=blob;f=stdlib/strtod_l.c;h=99c2af357efd7a1ee813f903148cd3c8b1d41f0a;hb=HEAD

**Comment by amosr** [comment]
### TODO

Test against `strtod` instead of `read::Double`. I don't trust read any more, but strtod is surprisingly robust.

Test `read::Double` and attoparsec against `strtod`.

Change from approximate equality in tests: https://github.com/ambiata/anemone/blob/master/test/Test/Anemone/Foreign/Strtod.hs#L67
approximate is only testing that the first 7 digits (22 bits) are correct, which seems way too coarse.

Some sort of round-trip test for going to string and back. I don't expect this one to be exact - maybe approximate equality is appropriate here.

### Larger questions
How much precision do we need from our double parsing code?
Given how complicated `strtod` is, I don't expect `read::Double` and attoparsec to be giving that level of bit-precision.
But, when we're parsing doubles, do we really care about bit-level precision? I wouldn't think so.

At the moment we know this is giving *at least* 7 significant digits correctness, which isn't great, but maybe that's sufficient?

File: ambiata-anemone.cabal [hunk 2]
```diff
@@ -35,9 +34,6 @@ library
                        src
 
   exposed-modules:
-                       Anemone
-                       Anemone.Headers
-
```
Comment (amosr) [inline ambiata-anemone.cabal]: I removed the header file-embed - we weren't using it and it made compilation quite a bit slower.

File: bench/bench.hs [hunk 3]
```diff
@@ -106,9 +106,10 @@ bench_atoi
  where
   go_all nm f
    = bgroup nm
-   $ fmap (\str -> bench (show str) $ nf f str)
+   $ fmap (\str -> bench (show str) $ nf f (pad str))
    [ "0", "1", "-123", "123456", "-12345678", "1234567890", "-123456789012345", "1234567890123456789", "12345678901234567890"
    ]
+  pad str = str <> " (padding added) "
```
Comment (amosr) [inline bench/bench.hs]: I added this padding because hopefully in most real uses your buffer will be large enough to load the whole 128bits at a time. however it didn't make much difference to the benchmark results

Comment (amosr) [inline bench/bench.hs]: ideally would benchmark both padded and unpadded, but the benchmarks already take too long

**Comment by amosr** [comment]
Ok. So this currently promises at least 7 significant digits of precision (and probably delivers better). It's no *worse* than the current anemone parser. In the future it would be good to test against strtod and attoparsec, but I think this is fine to merge now.

**Comment by jystic** [comment]
👍

**Comment by erikd-ambiata** [comment]
Let me try building Walrus against this branch. There's a test in Walrus that specifically targets what this PR is supposed to address.

**Comment by erikd-ambiata** [comment]
Still not quite there. Attoparsec will quite happily parse "41015786993444291.e207" but Anemone barfs:
```
=== prop_parse_stupid_long_double from test/Test/Walrus/Core/Snapshot.hs:113 ===
*** Failed! Falsifiable (after 13 tests): 
"41015786993444291.e207"
(False,Left "Failed reading: Double cannot be parsed:\"41015786993444291.e207\"") /= 
(True,Left "Failed reading: Double cannot be parsed:\"41015786993444291.e207\"")
```
The generator that produced this is at https://github.com/ambiata/walrus/blob/master/walrus-core/test/Test/Walrus/Core/Arbitrary.hs#L238-L254

**Comment by amosr** [comment]
good catch.
hmm. is that really a sane double? `read` doesn't parse it, although `strtod` does.

```
λ read "41015786993444291.e207" :: Double
*** Exception: Prelude.read: no parse
```

**Comment by erikd-ambiata** [comment]
Yeah, see my update. I think Anemone should handle this even if GHC's `read` rejects it.

**Comment by amosr** [comment]
sounds reasonable. this shouldn't be a big change. will do it next wed

**Comment by erikd-ambiata** [comment]
And please feel free to copy that `genStupidLongDoubleString` generator into Anemone and write a test around it.

**Comment by amosr** [comment]
I might change it to test against `strtod` itself then. I'm doing a similar thing to that generator, but was generating a non-empty list after the dot
 
Another cool one: `1.e`

**Comment by jystic** [comment]
> Still not quite there. Attoparsec will quite happily parse "41015786993444291.e207" but Anemone barfs

While it might be useful to be able to parse all these crazy cases, I don't think we should let that hold up this PR, as this is strictly better than what we currently have.

I think we should merge this and any additional features can be added in a later PR.

/cc @nhibberd @markhibberd

**Comment by nhibberd** [comment]
If this covers everything that icicle can output seems like a good enough change to push through. Can revisit the edge cases in the future

**Comment by amosr** [comment]
I think it's worth merging this as-is, because it fixes the most pressing issue. But am going dark for the next week, so giving @jystic merge power on this

**Comment by jystic** [comment]
I'm going to merge this, we can keep improving it over time, will make the next PR easier to review in any case.

**Comment by erikd-ambiata** [comment]
> If this covers everything that icicle can output seems like a good enough change to push through.

Sure, but I'm not comfortable using this version in Blowfish because I suspect that the data scientists may be running Blowfish over input files produced by tools other than icicle. I can wait for the updated version from @amosr .
